# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/math-for-ml-dl',
                'doc_host': 'https://najmehtaleb.github.io',
                'git_url': 'https://github.com/najmehtaleb/math-for-ml-dl',
                'lib_path': 'math_for_ml_dl'},
  'syms': {}}