# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/math-ml-dl',
                'doc_host': 'https://najmehtaleb.github.io',
                'git_url': 'https://github.com/najmehtaleb/math-ml-dl',
                'lib_path': 'math_ml_dl'},
  'syms': {'math_ml_dl.core': {'math_ml_dl.core.foo': ('core.html#foo', 'math_ml_dl/core.py')}}}