project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar: 
    search: true 
    title: Math for Machine Learning
    left:
      - text: Home
        href: https://najmehtaleb.github.io/my-site/
    
    right:
      - icon: github
        href: https://github.com/najmehtaleb/math-for-ml-dl
      - icon: twitter
        href: https://twitter.com/NajmehTaleb
        
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
    - section: Linear Algebra
      contents: 
      - 01-linear-algebra/01-numpy.ipynb
      - 01-linear-algebra/02-matrices.ipynb
      - 01-linear-algebra/03-factorization.ipynb
      - 01-linear-algebra/04-statistics.ipynb
    - section: Probbaility
      contents: 
      - 02-probability/01-intro.ipynb
      - 02-probability/02-foundations.ipynb
      - 02-probability/03-distributions.ipynb
      - 02-probability/04-maximum_likelihood.ipynb
      - 02-probability/05-bayesian_probability.ipynb
      - 02-probability/06-information_theory.ipynb
    - section: Statistics
      contents: statistics/*
    - section: Calculus
      contents: calculus/*
    - section: Code
      contents: code/*
    - section: Definition
      contents: definition/*
    - section: References
      contents: references/*

  
metadata-files: [nbdev.yml]
