project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar: 
    search: true 
    title: "Math for ML"
    left:
      - text: Home
        href: "https://najmehtaleb.github.io/my-site/"
    right:
      - icon: github
        href: "https://github.com/najmehtaleb/math-for-ml-dl"
      - icon: twitter
        href: "https://twitter.com/NajmehTaleb"
        
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
    - section: Linear Algebra
      contents: linear-algebra/*
    - section: Probbaility
      contents: probability/*
    - section: Statistics
      contents: statistics/*
    - section: Calculus
      contents: calculus/*
    - section: Code
      contents: code/*
    - section: Definition
      contents: definition/*
    - section: References
      contents: references/*

  
metadata-files: [nbdev.yml]