project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Calculus"
        href: calculus/01_calculus.ipynb
      - text: "Linear Algebra"
        menu: 
        - linear-algebra/01_numpy.ipynb
        - linear-algebra/02_matrices.ipynb 
        - linear-algebra/03_factorization.ipynb 
        - linear-algebra/03_factorization.ipynb 
      - text: "Probability"
        href: probability/*
      - text: "Statistics"
        href: statistics/*        
      - text: "More"
        menu: 
          - definition/definition.ipynb
          - code/code.ipynb
          - references/references.ipynb
    right:
      - icon: github
        href: "https://github.com/najmehtaleb/math-for-ml-dl"
      - icon: twitter
        href: "https://twitter.com/NajmehTaleb"
        
    

metadata-files: [nbdev.yml]